sudo:required
services:
  - docker

before_install:
  - docker build -t meir192/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true meir192/react-test npm run test

after_success:
  - docker build -t meir192/multi-client -f ./client
  - docker build -t meir192/multi-nginx -f ./nginx
  - docker build -t meir192/multi-server -f ./server
  - docker build -t meir192/multi-worker -f ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --pasword-stdin
  # push images to docker hub
  - docker push meir192/multi-client
  - docker push meir192/multi-nginx
  - docker push meir192/multi-server
  - docker push meir192/multi-worker
